### PR TITLE
January 11 2024 Meeting

### PR DESCRIPTION
**Pull request by tkuhrt**

### CODE REVIEW

**Comment by swcurran** [comment]
I assume you noticed, but there is the old list of reviewers.

Have we settled on a new time for the meeting?

**Comment by swcurran** [comment]
Also — we should discuss who is to be assigned to what projects for the Annual Reports that are due.

**Comment by tkuhrt** [comment]
> I assume you noticed, but there is the old list of reviewers.

I will need to get the CODEOWNERS file (or the `toc` team) updated

> Have we settled on a new time for the meeting?

I didn't know we were looking for a new time.

> Also — we should discuss who is to be assigned to what projects for the Annual Reports that are due.

I wanted to include that and forgot. Thank you for the reminder.

**Comment by swcurran** [comment]
Conor mentioned that the current time conflicts with the Besu Maintainer meeting.

**Comment by ryjones** [comment]
> > I assume you noticed, but there is the old list of reviewers.
> 
> I will need to get the CODEOWNERS file (or the `toc` team) updated
> 
> > Have we settled on a new time for the meeting?
> 
> I didn't know we were looking for a new time.
> 
> > Also — we should discuss who is to be assigned to what projects for the Annual Reports that are due.
> 
> I wanted to include that and forgot. Thank you for the reminder.

fixed

**Comment by tkuhrt** [comment]
@ryjones : Can you merge this? I do not have the ability to override the checks.

**Pull request merged**
