### PR TITLE
Add Charter

### PR DESCRIPTION
**Pull request by ryjones**
This is a copy of the current Hyperledger Charter.

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
A rendered version is here: https://ryjones.github.io/tsc/

Please note, which making this file, I found two typos in the version published on the website. That version may not yet be updated when you attempt to compare them

**Review by dcmiddle — APPROVED** [review]

**Review by lehors — APPROVED** [review]
One could argue that this doc doesn't belong to the TSC and therefore shouldn't be in the TSC repo but other than that, LGTM.

**Comment by ryjones** [comment]
> One could argue that this doc doesn't belong to the TSC and therefore shouldn't be in the TSC repo but other than that, LGTM.

My thought was this is a governing document, and to include it for reference. Not that the TSC would be amending it here.

**Comment by ryjones** [comment]
Per request

**Pull request closed without merging**
