### PR TITLE
Update project-lifecycle.md

### PR DESCRIPTION
**Pull request by barriebyron**
Signed-off-by: Barrie Byron <barriebyron@gmail.com> 

TIL I learned about DCO sign-off requirement

thanks, @tkuhrt for the suggestions and help. I abandoned the first PR since I failed in my attempt at rebasing my forked branch

here's a new PR with all changes from https://github.com/hyperledger/tsc/pull/28#issuecomment-1076840027

### CODE REVIEW

**Comment by tkuhrt** [comment]
@ryjones : Any idea why DCO is failing? Is it due to the extra commentary on the DCO line?

**Comment by ryjones** [comment]
@tkuhrt correct. I fixed it

**Review by ryjones — APPROVED** [review]

**Review by tkuhrt — APPROVED** [review]
I am approving, but I would like @lehors to have a look, as I believe he may have been involved in this document from the beginning.

**Review by lehors — APPROVED** [review]
LGTM. This is a nice improvement.
Thanks.

**Pull request merged**
